version: '3'
services:

  keymanagergrpc:
    build:
      dockerfile: Dockerfile
      context: .
    image: priscilasanfer/key-manager-grpc:latest
    restart: on-failure
    container_name: key-manager-grpc
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - bcb
      - erp-itau
    environment:
      BCB_URL: http://bcb:8082/api/v1/pix/keys
      ITAU:URL: http://erp-itau:9091/api/v1/clientes
      DB_USER: postgres
      DB_PASSWORD: root
      DB_URL: jdbc:postgresql://postgres/keymanager

  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports: 
        - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports: 
        - 9091:9091

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keymanager
      POSTGRES_HOST: postgres

volumes:
  postgres-volume: